name             'homeserver'
maintainer       'james legg'
description      'Installs/Configures homebox'
version          '0.1.1'
depends          'google-authenticator'
depends          'sshd'
depends          'netatalk'
depends          'home'
depends          'kernel'
depends          'samba'
